# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "01_greeter.ipynb",
         "HelloSayer": "01_greeter.ipynb"}

modules = ["greeter.py"]

doc_url = "https://ruivalmeida.github.io/nbdev_presentation/"

git_url = "https://github.com/ruivalmeida/nbdev_presentation/tree/master/"

def custom_doc_links(name): return None
